[[main]]
name              = "Home"
identifier        = "home"
url               = "/"
weight            = 1

[[main]]
name              = "About"
identifier        = "about"
url               = "/about/"
weight            = 2

[[main]]
name              = "Talks"
identifier        = "talks"
url               = "/talks/"
weight            = 3

[[main]]
name              = "Categories"
identifier        = "categories"
url               = "/categories/"
weight            = 10

[[main]]
name              = "Contact"
identifier        = "contact"
url               = "/contact/"
weight            = 15

[[main]]
name              = "Subscribe via RSS"
identifier        = "subscribe"
url               = "https://sathyasays.com/index.xml"
weight            = 20
