baseURL: https://sathyasays.com/
theme: pure
title: sathyasays.com
defaultContentLanguage: en  # en/zh/...
footnoteReturnLinkContents: ↩
hasCJKLanguage: false
paginate: 10
enableEmoji: true
googleAnalytics: "UA-155085050-1"      # UA-XXXXXXXX-X 
permalinks:
  posts: /:year/:month/:filename/

taxonomies:
    category : categories
    tag : tags
    series : series
outputFormats:          # use for search. recommend not to modify 
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true
    
outputs:
    home: ["HTML","RSS","SearchIndex"]  # recommend not to modify
# sitemap
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    - identifier: home
      name: Home
      title: Home 
      url: /
      weight: 1

    - identifier: archives
      name: Archives
      title: Archives
      url: /posts
      weight: 2

    - identifier: categories
      name: Categories
      title: Categories
      url: /categories
      weight: 3

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags
      weight: 4

    - identifier: about
      name: About
      title: About
      url: /about
      weight: 5


params:
  since: 2007
  dateFormatToUse: "2006-01-02"
  enablePostCopyright: false
  # the directory under content folder that you want to render
  mainSections: ["post"]
  # Enable/Disable menu icons
  # Icon Reference: http://blog.cofess.com/hexo-theme-pure/iconfont/demo_fontclass.html
  enableMathJax: false #Enable mathjax support, to use mathematical notations
  highlightjs:
    langs: ["python", "bash"] # refer to http://staticfile.org/, search highlight.js, already have highlight.min.js
    
  menuIcons:
    enable: true  # 是否启用导航菜单图标
    home: icon-home-fill
    archives: icon-archives-fill
    categories: icon-folder
    tags: icon-tags
    repository: icon-project
    books: icon-book-fill
    links: icon-friendship
    about: icon-cup-fill

  # profile
  profile:
    enabled: true # Whether to show profile bar
    avatar: https://www.gravatar.com/avatar/1375f202e61682cc4963295f4b0430dc?s=128&d=identicon&r=PG
    gravatar: sathya@sathyasays.com # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
    author: Sathyajith Bhat
    author_title: Author, AWS Community Hero and DevOps Specialist
    author_description: 
    location: Bucharest, Romania
    follow: https://github.com/sathyabhat
    # Social Links
    social:
      links:
        github: https://github.com/sathyabhat
        # weibo: http://weibo.com/{yourid}
        twitter: https://twitter.com/sathyabhat
        facebook: https://facebook.com/sathyabhat
        linkedin: https://linkedin.com/in/sathyabhat
        rss: /index.xml
      link_tooltip: true # enable the social link tooltip, options: true, false
  # Site
  site:
    logo:
      enabled: true
      width: 40
      height: 40
      url: favicon.ico
    title: Sathya Says # 页面title
    favicon: favicon.ico
    board: <p>enjoy~</p> # 公告牌

  # Share
  # weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
  share:
    enable: true # 是否启用分享
    sites: twitter,facebook,linkedin # PC端显示的分享图标
    mobile_sites: twitter,facebook,linkedin # 移动端显示的分享图标

  # Comment
  comment:
    type: disqus # type disqus/gitalk/valine 启用哪种评论系统
    disqus: sathyasays # enter disqus shortname here
    gitalk: # gitalk. https://gitalk.github.io/
      owner: #必须. GitHub repository 所有者，可以是个人或者组织。
      admin: #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
      repo:  #必须. GitHub repository.
      ClientID: #必须. GitHub Application Client ID.
      ClientSecret: #必须. GitHub Application Client Secret.
    valine: # Valine. https://valine.js.org
      appid: # your leancloud application appid
      appkey: # your leancloud application appkey
      notify: # mail notifier , https://github.com/xCss/Valine/wiki
      verify: # Verification code
      placeholder: enjoy~ # comment box placeholder
      avatar: mm # gravatar style
      meta: nick,mail # custom comment header
      pageSize: 10 # pagination size
      visitor: false # Article reading statistic https://valine.js.org/visitor.html

  # Donate
  donate:
    enable: false
    # 微信打赏
    wechatpay:
      qrcode: donate/wechatpayimg.png
      title: 微信支付
    # 支付宝打赏
    alipay:
      qrcode: donate/alipayimg.png
      title: 支付宝

  # PV
  pv:
    busuanzi:
      enable: false # 不蒜子统计
    leancloud:
      enable: false # leancloud统计
      app_id: # leancloud <AppID>
      app_key: # leancloud <AppKey>

  # wordcount
  postCount:
    enable: true
    wordcount: true # 文章字数统计
    min2read: true # read time 阅读时长预计

  # config
  config:
    skin: theme-black # theme color default is white. other type [theme-black,theme-blue,theme-green,theme-purple]
    layout: main-center # main-left main-center main-right
    excerpt_link: Read More
    toc: true

  # Sidebar
  sidebar: right

  # Search
  search:
    enable: true # enable search. thanks for https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/master/source/js/insight.js

  # Sidebar only the following widgets. you can remove any you don't like it.
  widgets:
    - category
    - tag
    - recent_posts
